import type { PRDData } from '../lib/prdTemplate'
import type { Node, Edge } from '@xyflow/react'
import type { Artboard } from '../stores/wireframeStore'

interface BundleData {
    projectName: string
    prd: PRDData | null
    flowchart: { nodes: Node[], edges: Edge[] } | null
    artboards: Artboard[]
}

export function generateBundleMarkdown(data: BundleData): string {
    const sections: string[] = []

    // Header
    sections.push(`# 📦 AI Development Context Bundle

> **Project:** ${data.projectName}
> **Generated:** ${new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}
> **Generated by:** antifigma

---
`)

    // PRD Section
    if (data.prd) {
        const coreFeatures = data.prd.coreFeatures
            .filter(f => f.trim())
            .map((f, i) => `${i + 1}. ${f}`)
            .join('\n')

        const outOfScope = data.prd.outOfScope
            .filter(f => f.trim())
            .map(f => `- ❌ ${f}`)
            .join('\n')

        sections.push(`## 📝 Product Requirements Document

### Problem Statement
${data.prd.problemStatement}

### Target Users
${data.prd.targetUser}

### Core Features (MVP Scope)
${coreFeatures || '_Belum didefinisikan_'}

### Out of Scope (Parking Lot)
${outOfScope || '_Tidak ada item_'}

> ⚠️ Items di atas TIDAK termasuk dalam MVP.

${data.prd.techPreferences ? `### Tech Stack
${data.prd.techPreferences}
` : ''}
${data.prd.databaseSchema ? `### Database Schema
\`\`\`
${data.prd.databaseSchema}
\`\`\`
` : ''}
---
`)
    } else {
        sections.push(`## 📝 Product Requirements Document

_PRD belum dibuat. Silakan buat PRD terlebih dahulu._

---
`)
    }

    // Flowchart Section
    if (data.flowchart && data.flowchart.nodes.length > 0) {
        const nodeDescriptions = data.flowchart.nodes
            .map(n => `- **${n.type?.toUpperCase() || 'NODE'}:** ${(n.data as { label?: string })?.label || n.id}`)
            .join('\n')

        const connectionDescriptions = data.flowchart.edges
            .map(e => {
                const source = data.flowchart!.nodes.find(n => n.id === e.source)
                const target = data.flowchart!.nodes.find(n => n.id === e.target)
                const sourceLabel = (source?.data as { label?: string })?.label || e.source
                const targetLabel = (target?.data as { label?: string })?.label || e.target
                return `- ${sourceLabel} → ${targetLabel}`
            })
            .join('\n')

        sections.push(`## 📊 System Architecture / Flowchart

### Components (${data.flowchart.nodes.length} nodes)
${nodeDescriptions}

### Connections (${data.flowchart.edges.length} edges)
${connectionDescriptions || '_Tidak ada koneksi_'}

---
`)
    } else {
        sections.push(`## 📊 System Architecture / Flowchart

_Flowchart belum dibuat. Silakan buat flowchart terlebih dahulu._

---
`)
    }

    // Wireframe Section
    if (data.artboards.length > 0) {
        const artboardDescriptions = data.artboards
            .map(a => {
                const shapeDescriptions = a.shapes.length > 0
                    ? a.shapes.map(s => `  - ${s.type}${s.text ? `: "${s.text}"` : ''} at (${Math.round(s.x)}, ${Math.round(s.y)})`).join('\n')
                    : '  _Tidak ada elemen_'
                return `### ${a.name} (${a.width}x${a.height})
${shapeDescriptions}`
            })
            .join('\n\n')

        sections.push(`## 🎨 Wireframes

${artboardDescriptions}

---
`)
    } else {
        sections.push(`## 🎨 Wireframes

_Wireframe belum dibuat. Silakan buat wireframe terlebih dahulu._

---
`)
    }

    // File Structure Suggestion
    if (data.prd?.techPreferences) {
        const isReact = data.prd.techPreferences.toLowerCase().includes('react')
        const isNext = data.prd.techPreferences.toLowerCase().includes('next')
        const isVite = data.prd.techPreferences.toLowerCase().includes('vite')

        let structure = ''
        if (isNext) {
            structure = `\`\`\`
src/
├── app/
│   ├── layout.tsx
│   ├── page.tsx
│   └── globals.css
├── components/
│   ├── ui/
│   └── layout/
├── lib/
│   └── utils.ts
└── types/
    └── index.ts
\`\`\``
        } else if (isReact || isVite) {
            structure = `\`\`\`
src/
├── components/
│   ├── ui/
│   └── layout/
├── pages/ or modules/
├── hooks/
├── stores/
├── lib/
├── types/
└── App.tsx
\`\`\``
        }

        if (structure) {
            sections.push(`## 📁 Suggested File Structure

${structure}

---
`)
        }
    }

    // AI Instructions
    sections.push(`## 🤖 Notes for AI Assistant

Saat membantu development project ini:

1. **Scope Management**
   - Selalu refer ke Core Features untuk MVP
   - Jika ada request fitur baru, tanyakan masuk MVP atau Parking Lot
   
2. **Architecture**
   - Ikuti flowchart yang sudah didefinisikan
   - Setiap node dalam flowchart adalah komponen/screen yang perlu dibuat
   
3. **UI/UX**
   - Gunakan wireframe sebagai referensi layout
   - Posisi dan elemen dalam wireframe adalah panduan struktur UI

4. **Consistency**
   - Gunakan naming convention yang konsisten
   - Follow tech stack yang sudah ditentukan

---

*Context bundle ini di-generate otomatis oleh antifigma.*
*Copy seluruh konten ini ke AI assistant untuk development yang konsisten.*
`)

    return sections.join('\n')
}

export function generateQuickSummary(data: BundleData): {
    hasPRD: boolean
    hasFlowchart: boolean
    hasWireframes: boolean
    featuresCount: number
    nodesCount: number
    artboardsCount: number
    shapesCount: number
} {
    return {
        hasPRD: !!data.prd,
        hasFlowchart: !!data.flowchart && data.flowchart.nodes.length > 0,
        hasWireframes: data.artboards.length > 0,
        featuresCount: data.prd?.coreFeatures.filter(f => f.trim()).length || 0,
        nodesCount: data.flowchart?.nodes.length || 0,
        artboardsCount: data.artboards.length,
        shapesCount: data.artboards.reduce((sum, a) => sum + a.shapes.length, 0),
    }
}
