export interface PRDData {
    projectName: string
    problemStatement: string
    targetUser: string
    coreFeatures: string[]
    outOfScope: string[]
    techPreferences: string
    databaseSchema: string
}

export function generatePRDMarkdown(data: PRDData): string {
    const coreFeatures = data.coreFeatures
        .filter((f: string) => f.trim())
        .map((f: string, i: number) => `${i + 1}. ${f}`)
        .join('\n')

    const outOfScope = data.outOfScope
        .filter((f: string) => f.trim())
        .map((f: string) => `- ❌ ${f}`)
        .join('\n')

    const markdown = `# PRD: ${data.projectName}

> Generated by antifigma
> Date: ${new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}

---

## 1. Problem Statement

${data.problemStatement}

---

## 2. Target Users

${data.targetUser}

---

## 3. Core Features (MVP Scope)

${coreFeatures || '_Belum didefinisikan_'}

---

## 4. Out of Scope (Parking Lot)

${outOfScope || '_Tidak ada item_'}

> ⚠️ Items di atas TIDAK termasuk dalam MVP. Simpan untuk iterasi berikutnya.

---

${data.techPreferences ? `## 5. Tech Stack Preferences

${data.techPreferences}

---

` : ''}${data.databaseSchema ? `## ${data.techPreferences ? '6' : '5'}. Database Schema

\`\`\`
${data.databaseSchema}
\`\`\`

---

` : ''}## Notes for AI Assistant

Saat membantu development project ini, mohon:
1. Selalu refer ke scope yang sudah didefinisikan di atas
2. Jika ada fitur baru yang diminta, tanyakan apakah masuk MVP atau Parking Lot
3. Prioritaskan Core Features sebelum menambah yang baru
4. Gunakan tech stack yang sudah didefinisikan jika ada

---

*PRD ini di-generate otomatis dan bisa di-update sesuai kebutuhan.*
`

    return markdown
}

export function generateContextBundle(data: PRDData): string {
    const prdMarkdown = generatePRDMarkdown(data)

    const bundle = `# 📦 AI Development Context Bundle

${prdMarkdown}

---

## Quick Reference

**Project:** ${data.projectName}
**Core Features:** ${data.coreFeatures.filter((f: string) => f.trim()).length} items
**Out of Scope:** ${data.outOfScope.filter((f: string) => f.trim()).length} items
${data.techPreferences ? `**Tech Stack:** ${data.techPreferences.split('\n')[0]}...` : ''}

---

*Copy this entire context to your AI assistant for consistent development.*
`

    return bundle
}
